# Installing Dependencies

In [1]:
import sys
print("Python executable:", sys.executable)

Python executable: /venv/main/bin/python

In [2]:
# Install missing dependencies for evaluate's ROUGE metric
import sys
!{sys.executable} -m pip install polyglot pyicu pycld2 morfessor rouge_score nltk absl-py tqdm bert_score

Collecting polyglot
  Downloading polyglot-16.7.4.tar.gz (126 kB)
  Preparing metadata (setup.py) ... done
Collecting pyicu
  Downloading pyicu-2.15.3.tar.gz (267 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pycld2
  Downloading pycld2-0.42-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.5 kB)
Collecting morfessor
  Downloading Morfessor-2.0.6-py3-none-any.whl.metadata (628 bytes)
Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting nltk
  Downloading nltk-3.9.2-py3-none-any.whl.metadata (3.2 kB)
Collecting absl-py
  Downloading absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: tqdm in /venv/main/lib/python3.10/site-packages (4.67.1)
Collecting bert_score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy in /venv/main/lib/python3.10/site-packages (from rouge_score) (2.1.2)
Requirement already satisfied: six>=1.14.0 in /venv/main/lib/python3.10/site-packages (from rouge_score) (1.17.0)
Collecting click (from nltk)
  Downloading click-8.3.0-py3-none-any.whl.metadata (2.6 kB)
Collecting joblib (from nltk)
  Downloading joblib-1.5.2-py3-none-any.whl.metadata (5.6 kB)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2025.10.23-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Requirement already satisfied: torch>=1.0.0 in /venv/main/lib/python3.10/site-packages (from bert_score) (2.6.0+cu124)
Collecting pandas>=1.0.1 (from bert_score)
  Downloading pandas-2.3.3-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
Collecting transformers>=3.0.0 (from bert_score)
  Downloading transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: requests in /venv/main/lib/python3.10/site-packages (from bert_score) (2.32.5)
Collecting matplotlib (from bert_score)
  Downloading matplotlib-3.10.7-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Requirement already satisfied: packaging>=20.9 in /venv/main/lib/python3.10/site-packages (from bert_score) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /venv/main/lib/python3.10/site-packages (from pandas>=1.0.1->bert_score) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas>=1.0.1->bert_score)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas>=1.0.1->bert_score)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: filelock in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (4.15.0)
Requirement already satisfied: networkx in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (3.3)
Requirement already satisfied: jinja2 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (3.1.4)
Requirement already satisfied: fsspec in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (2025.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /venv/main/lib/python3.10/site-packages (from torch>=1.0.0->bert_score) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /venv/main/lib/python3.10/site-packages (from sympy==1.13.1->torch>=1.0.0->bert_score) (1.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /venv/main/lib/python3.10/site-packages (from transformers>=3.0.0->bert_score) (0.34.4)
Requirement already satisfied: pyyaml>=5.1 in /venv/main/lib/python3.10/site-packages (from transformers>=3.0.0->bert_score) (6.0.2)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers>=3.0.0->bert_score)
  Downloading tokenizers-0.22.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting safetensors>=0.4.3 (from transformers>=3.0.0->bert_score)
  Downloading safetensors-0.6.2-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /venv/main/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers>=3.0.0->bert_score) (1.1.9)
Requirement already satisfied: MarkupSafe>=2.0 in /venv/main/lib/python3.10/site-packages (from jinja2->torch>=1.0.0->bert_score) (2.1.5)
Collecting contourpy>=1.0.1 (from matplotlib->bert_score)
  Downloading contourpy-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->bert_score)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->bert_score)
  Downloading fonttools-4.60.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (112 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->bert_score)
  Downloading kiwisolver-1.4.9-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (6.3 kB)
Requirement already satisfied: pillow>=8 in /venv/main/lib/python3.10/site-packages (from matplotlib->bert_score) (11.0.0)
Collecting pyparsing>=3 (from matplotlib->bert_score)
  Downloading pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /venv/main/lib/python3.10/site-packages (from requests->bert_score) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /venv/main/lib/python3.10/site-packages (from requests->bert_score) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /venv/main/lib/python3.10/site-packages (from requests->bert_score) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /venv/main/lib/python3.10/site-packages (from requests->bert_score) (2025.8.3)
Downloading pycld2-0.42-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 41.6 MB/s  0:00:00m0:00:01
Downloading Morfessor-2.0.6-py3-none-any.whl (35 kB)
Downloading nltk-3.9.2-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 16.6 MB/s  0:00:00
Downloading absl_py-2.3.1-py3-none-any.whl (135 kB)
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
Downloading pandas-2.3.3-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 61.7 MB/s  0:00:006m0:00:01
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading regex-2025.10.23-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (791 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 791.5/791.5 kB 8.0 MB/s  0:00:00
Downloading transformers-4.57.1-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 61.2 MB/s  0:00:00
Downloading tokenizers-0.22.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 31.0 MB/s  0:00:00
Downloading safetensors-0.6.2-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (485 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Downloading click-8.3.0-py3-none-any.whl (107 kB)
Downloading joblib-1.5.2-py3-none-any.whl (308 kB)
Downloading matplotlib-3.10.7-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 53.9 MB/s  0:00:00
Downloading contourpy-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (325 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.60.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 41.1 MB/s  0:00:00
Downloading kiwisolver-1.4.9-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 11.8 MB/s  0:00:00
Downloading pyparsing-3.2.5-py3-none-any.whl (113 kB)
Building wheels for collected packages: polyglot, pyicu, rouge_score
  DEPRECATION: Building 'polyglot' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'polyglot'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  Building wheel for polyglot (setup.py) ... done
  Created wheel for polyglot: filename=polyglot-16.7.4-py2.py3-none-any.whl size=52641 sha256=5798e8fe7da1b7e897f5a8dc6d29ea25286987742587bba377a7b8eba6f015b7
  Stored in directory: /root/.cache/pip/wheels/aa/92/4a/b172589446ba537db3bdb9a1f2204f27fe71217981c14ac368
  Building wheel for pyicu (pyproject.toml) ... done
  Created wheel for pyicu: filename=pyicu-2.15.3-cp310-cp310-linux_x86_64.whl size=539142 sha256=3d86275d20f09e29f3a460d09fe063bfd9e42143f4117cf9885bc6bf621014ca
  Stored in directory: /root/.cache/pip/wheels/b5/3b/ee/8f690f939ac0ddabf203153124e11d068c2d5b0ccc4dfcb375
  DEPRECATION: Building 'rouge_score' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'rouge_score'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24987 sha256=4757aa7d358be3bf92b8e12e670a85b610d73888bcf626a1f7fa46724c328ba0
  Stored in directory: /root/.cache/pip/wheels/5f/dd/89/461065a73be61a532ff8599a28e9beef17985c9e9c31e541b4
Successfully built polyglot pyicu rouge_score
Installing collected packages: pytz, pyicu, pycld2, polyglot, morfessor, tzdata, safetensors, regex, pyparsing, kiwisolver, joblib, fonttools, cycler, contourpy, click, absl-py, pandas, nltk, matplotlib, tokenizers, rouge_score, transformers, bert_score
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23/23 [bert_score]3 [bert_score]s]
Successfully installed absl-py-2.3.1 bert_score-0.3.13 click-8.3.0 contourpy-1.3.2 cycler-0.12.1 fonttools-4.60.1 joblib-1.5.2 kiwisolver-1.4.9 matplotlib-3.10.7 morfessor-2.0.6 nltk-3.9.2 pandas-2.3.3 polyglot-16.7.4 pycld2-0.42 pyicu-2.15.3 pyparsing-3.2.5 pytz-2025.2 regex-2025.10.23 rouge_score-0.1.2 safetensors-0.6.2 tokenizers-0.22.1 transformers-4.57.1 tzdata-2025.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [3]:
import sys
!{sys.executable} -m pip install transformers bitsandbytes peft accelerate datasets trl evaluate

Requirement already satisfied: transformers in /venv/main/lib/python3.10/site-packages (4.57.1)
Collecting bitsandbytes
  Downloading bitsandbytes-0.48.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting peft
  Downloading peft-0.17.1-py3-none-any.whl.metadata (14 kB)
Collecting accelerate
  Downloading accelerate-1.11.0-py3-none-any.whl.metadata (19 kB)
Collecting datasets
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Collecting trl
  Downloading trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: filelock in /venv/main/lib/python3.10/site-packages (from transformers) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /venv/main/lib/python3.10/site-packages (from transformers) (0.34.4)
Requirement already satisfied: numpy>=1.17 in /venv/main/lib/python3.10/site-packages (from transformers) (2.1.2)
Requirement already satisfied: packaging>=20.0 in /venv/main/lib/python3.10/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /venv/main/lib/python3.10/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /venv/main/lib/python3.10/site-packages (from transformers) (2025.10.23)
Requirement already satisfied: requests in /venv/main/lib/python3.10/site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /venv/main/lib/python3.10/site-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /venv/main/lib/python3.10/site-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /venv/main/lib/python3.10/site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /venv/main/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /venv/main/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /venv/main/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.9)
Requirement already satisfied: torch<3,>=2.3 in /venv/main/lib/python3.10/site-packages (from bitsandbytes) (2.6.0+cu124)
Requirement already satisfied: networkx in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (3.3)
Requirement already satisfied: jinja2 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /venv/main/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /venv/main/lib/python3.10/site-packages (from sympy==1.13.1->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: psutil in /venv/main/lib/python3.10/site-packages (from peft) (7.0.0)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-22.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.2 kB)
Collecting dill<0.4.1,>=0.3.0 (from datasets)
  Downloading dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /venv/main/lib/python3.10/site-packages (from datasets) (2.3.3)
Collecting httpx<1.0.0 (from datasets)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting xxhash (from datasets)
  Downloading xxhash-3.6.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Collecting anyio (from httpx<1.0.0->datasets)
  Downloading anyio-4.11.0-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: certifi in /venv/main/lib/python3.10/site-packages (from httpx<1.0.0->datasets) (2025.8.3)
Collecting httpcore==1.* (from httpx<1.0.0->datasets)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in /venv/main/lib/python3.10/site-packages (from httpx<1.0.0->datasets) (3.10)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0->datasets)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting async-timeout<6.0,>=4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets)
  Downloading async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)
Collecting attrs>=17.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp310-cp310-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets)
  Downloading propcache-0.4.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets)
  Downloading yarl-1.22.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (75 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /venv/main/lib/python3.10/site-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /venv/main/lib/python3.10/site-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /venv/main/lib/python3.10/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.0)
Collecting sniffio>=1.1 (from anyio->httpx<1.0.0->datasets)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /venv/main/lib/python3.10/site-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (2.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /venv/main/lib/python3.10/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /venv/main/lib/python3.10/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /venv/main/lib/python3.10/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /venv/main/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading bitsandbytes-0.48.1-py3-none-manylinux_2_24_x86_64.whl (60.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 MB 147.8 MB/s  0:00:00m0:00:0100:01
Downloading peft-0.17.1-py3-none-any.whl (504 kB)
Downloading accelerate-1.11.0-py3-none-any.whl (375 kB)
Downloading datasets-4.3.0-py3-none-any.whl (506 kB)
Downloading dill-0.4.0-py3-none-any.whl (119 kB)
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
Downloading trl-0.24.0-py3-none-any.whl (423 kB)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
Downloading aiohttp-3.13.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 103.7 MB/s  0:00:00
Downloading async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Downloading multidict-6.7.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (241 kB)
Downloading yarl-1.22.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (346 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
Downloading frozenlist-1.8.0-cp310-cp310-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (219 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading propcache-0.4.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (196 kB)
Downloading pyarrow-22.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (47.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 167.3 MB/s  0:00:00 eta 0:00:01
Downloading anyio-4.11.0-py3-none-any.whl (109 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading xxhash-3.6.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
Installing collected packages: xxhash, sniffio, pyarrow, propcache, multidict, h11, frozenlist, dill, attrs, async-timeout, aiohappyeyeballs, yarl, multiprocess, httpcore, anyio, aiosignal, httpx, aiohttp, bitsandbytes, accelerate, peft, datasets, trl, evaluate
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24/24 [evaluate]/24 [evaluate]e]s]
Successfully installed accelerate-1.11.0 aiohappyeyeballs-2.6.1 aiohttp-3.13.1 aiosignal-1.4.0 anyio-4.11.0 async-timeout-5.0.1 attrs-25.4.0 bitsandbytes-0.48.1 datasets-4.3.0 dill-0.4.0 evaluate-0.4.6 frozenlist-1.8.0 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 multidict-6.7.0 multiprocess-0.70.16 peft-0.17.1 propcache-0.4.1 pyarrow-22.0.0 sniffio-1.3.1 trl-0.24.0 xxhash-3.6.0 yarl-1.22.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [4]:
import transformers
print("Transformers version:", transformers.__version__)

Transformers version: 4.57.1

In [2]:
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, GenerationConfig, TrainingArguments, Trainer
import torch
import time
import evaluate
import pandas as pd
import numpy as np

# Load the model and Tokenizer

In [6]:
import torch
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))

1
NVIDIA RTX A6000

In [7]:
from huggingface_hub import login

login(token="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")

In [8]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

model_name = "google/gemma-7b"

# Define 4-bit quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,               # Use 4-bit quantization
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

# Load model with quantization
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map=None,               # Or {"":0} if single GPU
    torch_dtype=torch.float16
)

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token  # Helps avoid padding errors

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/20.9k [00:00<?, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/2.11G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/33.6k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

# Model parameters count

In [9]:
def print_number_of_trainable_model_parameters(model):
    trainable_model_params = 0
    all_model_params = 0
    for _, param in model.named_parameters():
        all_model_params += param.numel()
        if param.requires_grad:
            trainable_model_params += param.numel()
    return f"trainable model parameters: {trainable_model_params}\nall model parameters: {all_model_params}\npercentage of trainable model parameters: {100 * trainable_model_params / all_model_params:.2f}%"
print(print_number_of_trainable_model_parameters(model))

trainable model parameters: 786607104
all model parameters: 4662144000
percentage of trainable model parameters: 16.87%

# Instruction fine tuning

##  load the dataset

In [10]:
from datasets import load_dataset, concatenate_datasets

# 🔤 Define the language split for Hindi (Updesh naming convention)
LANG_CODE = "asm_Beng"  # language split code

# 🧩 List of all subsets to include
subsets = [
    "summarization",                  # ✅ Core summarization task
    "rc",                             # ✅ Reading comprehension → summary-like compression
    "multihop_reasoning",             # ✅ Multi-context reasoning, similar to abstractive synthesis
    "cultural_multihop_reasoning",    # ✅ Adds diversity and cross-cultural reasoning depth
    "dialog_gen",                     # ✅ Conversational summarization & generative response
    "creative_writing",               # ✅ Enhances fluency and narrative coherence
]


# 🧠 Load all subsets and combine them into a single dataset
train_datasets = []

for subset in subsets:
    print(f"🔹 Loading subset: {subset} for Hindi...")
    try:
        ds = load_dataset("microsoft/Updesh_beta", subset, split=LANG_CODE)
        train_datasets.append(ds)
    except Exception as e:
        print(f"⚠️ Skipping {subset} due to error: {e}")



from datasets import concatenate_datasets

# Drop `id` column if needed and retry concatenation
cleaned_datasets = []
for ds in train_datasets:
    if "id" in ds.column_names:
        ds = ds.remove_columns(["id"])
    cleaned_datasets.append(ds)

train_dataset = concatenate_datasets(cleaned_datasets)

print(f"✅ Combined Bengali Dataset Loaded: {len(train_dataset)} samples across all subsets.")

🔹 Loading subset: summarization for Hindi...

README.md: 0.00B [00:00, ?B/s]

summarization/asm_Beng-00000-of-00001.pa(…):   0%|          | 0.00/53.8M [00:00<?, ?B/s]

summarization/ben_Beng-00000-of-00001.pa(…):   0%|          | 0.00/121M [00:00<?, ?B/s]

summarization/eng_Latn-00000-of-00001.pa(…):   0%|          | 0.00/352M [00:00<?, ?B/s]

summarization/guj_Gujr-00000-of-00001.pa(…):   0%|          | 0.00/28.2M [00:00<?, ?B/s]

summarization/hin_Deva-00000-of-00001.pa(…):   0%|          | 0.00/118M [00:00<?, ?B/s]

summarization/kan_Knda-00000-of-00001.pa(…):   0%|          | 0.00/81.0M [00:00<?, ?B/s]

summarization/mal_Mlym-00000-of-00001.pa(…):   0%|          | 0.00/87.9M [00:00<?, ?B/s]

summarization/mar_Deva-00000-of-00001.pa(…):   0%|          | 0.00/73.0M [00:00<?, ?B/s]

summarization/npi_Deva-00000-of-00001.pa(…):   0%|          | 0.00/44.8M [00:00<?, ?B/s]

summarization/ory_Orya-00000-of-00001.pa(…):   0%|          | 0.00/32.0M [00:00<?, ?B/s]

summarization/pan_Guru-00000-of-00001.pa(…):   0%|          | 0.00/48.5M [00:00<?, ?B/s]

summarization/tam_Taml-00000-of-00001.pa(…):   0%|          | 0.00/98.5M [00:00<?, ?B/s]

summarization/tel_Telu-00000-of-00001.pa(…):   0%|          | 0.00/82.1M [00:00<?, ?B/s]

summarization/urd_Arab-00000-of-00001.pa(…):   0%|          | 0.00/16.9M [00:00<?, ?B/s]

Generating asm_Beng split:   0%|          | 0/16134 [00:00<?, ? examples/s]

Generating ben_Beng split:   0%|          | 0/16372 [00:00<?, ? examples/s]

Generating eng_Latn split:   0%|          | 0/16372 [00:00<?, ? examples/s]

Generating guj_Gujr split:   0%|          | 0/16367 [00:00<?, ? examples/s]

Generating hin_Deva split:   0%|          | 0/16364 [00:00<?, ? examples/s]

Generating kan_Knda split:   0%|          | 0/16365 [00:00<?, ? examples/s]

Generating mal_Mlym split:   0%|          | 0/16354 [00:00<?, ? examples/s]

Generating mar_Deva split:   0%|          | 0/16371 [00:00<?, ? examples/s]

Generating npi_Deva split:   0%|          | 0/15717 [00:00<?, ? examples/s]

Generating ory_Orya split:   0%|          | 0/16367 [00:00<?, ? examples/s]

Generating pan_Guru split:   0%|          | 0/16374 [00:00<?, ? examples/s]

Generating tam_Taml split:   0%|          | 0/16369 [00:00<?, ? examples/s]

Generating tel_Telu split:   0%|          | 0/16367 [00:00<?, ? examples/s]

Generating urd_Arab split:   0%|          | 0/16369 [00:00<?, ? examples/s]

🔹 Loading subset: rc for Hindi...

rc/asm_Beng-00000-of-00002.parquet:   0%|          | 0.00/95.9M [00:00<?, ?B/s]

rc/asm_Beng-00001-of-00002.parquet:   0%|          | 0.00/95.6M [00:00<?, ?B/s]

rc/ben_Beng-00000-of-00001.parquet:   0%|          | 0.00/166M [00:00<?, ?B/s]

rc/guj_Gujr-00000-of-00001.parquet:   0%|          | 0.00/136M [00:00<?, ?B/s]

rc/hin_Deva-00000-of-00002.parquet:   0%|          | 0.00/109M [00:00<?, ?B/s]

rc/hin_Deva-00001-of-00002.parquet:   0%|          | 0.00/109M [00:00<?, ?B/s]

rc/kan_Knda-00000-of-00001.parquet:   0%|          | 0.00/124M [00:00<?, ?B/s]

rc/mal_Mlym-00000-of-00001.parquet:   0%|          | 0.00/136M [00:00<?, ?B/s]

rc/mar_Deva-00000-of-00002.parquet:   0%|          | 0.00/108M [00:00<?, ?B/s]

rc/mar_Deva-00001-of-00002.parquet:   0%|          | 0.00/108M [00:00<?, ?B/s]

rc/npi_Deva-00000-of-00002.parquet:   0%|          | 0.00/102M [00:00<?, ?B/s]

rc/npi_Deva-00001-of-00002.parquet:   0%|          | 0.00/100M [00:00<?, ?B/s]

rc/ory_Orya-00000-of-00001.parquet:   0%|          | 0.00/122M [00:00<?, ?B/s]

rc/pan_Guru-00000-of-00001.parquet:   0%|          | 0.00/139M [00:00<?, ?B/s]

rc/tam_Taml-00000-of-00002.parquet:   0%|          | 0.00/99.9M [00:00<?, ?B/s]

rc/tam_Taml-00001-of-00002.parquet:   0%|          | 0.00/98.8M [00:00<?, ?B/s]

rc/tel_Telu-00000-of-00001.parquet:   0%|          | 0.00/164M [00:00<?, ?B/s]

rc/urd_Arab-00000-of-00001.parquet:   0%|          | 0.00/179M [00:00<?, ?B/s]

Generating asm_Beng split:   0%|          | 0/49659 [00:00<?, ? examples/s]

Generating ben_Beng split:   0%|          | 0/49922 [00:00<?, ? examples/s]

Generating guj_Gujr split:   0%|          | 0/49928 [00:00<?, ? examples/s]

Generating hin_Deva split:   0%|          | 0/49582 [00:00<?, ? examples/s]

Generating kan_Knda split:   0%|          | 0/49912 [00:00<?, ? examples/s]

Generating mal_Mlym split:   0%|          | 0/49962 [00:00<?, ? examples/s]

Generating mar_Deva split:   0%|          | 0/49809 [00:00<?, ? examples/s]

Generating npi_Deva split:   0%|          | 0/49634 [00:00<?, ? examples/s]

Generating ory_Orya split:   0%|          | 0/49804 [00:00<?, ? examples/s]

Generating pan_Guru split:   0%|          | 0/49939 [00:00<?, ? examples/s]

Generating tam_Taml split:   0%|          | 0/49922 [00:00<?, ? examples/s]

Generating tel_Telu split:   0%|          | 0/49942 [00:00<?, ? examples/s]

Generating urd_Arab split:   0%|          | 0/49521 [00:00<?, ? examples/s]

🔹 Loading subset: multihop_reasoning for Hindi...

multihop_reasoning/asm_Beng-00000-of-000(…):   0%|          | 0.00/72.7M [00:00<?, ?B/s]

multihop_reasoning/ben_Beng-00000-of-000(…):   0%|          | 0.00/63.3M [00:00<?, ?B/s]

multihop_reasoning/eng_Latn-00000-of-000(…):   0%|          | 0.00/82.0M [00:00<?, ?B/s]

multihop_reasoning/guj_Gujr-00000-of-000(…):   0%|          | 0.00/36.8M [00:00<?, ?B/s]

multihop_reasoning/hin_Deva-00000-of-000(…):   0%|          | 0.00/78.5M [00:00<?, ?B/s]

multihop_reasoning/kan_Knda-00000-of-000(…):   0%|          | 0.00/76.1M [00:00<?, ?B/s]

multihop_reasoning/mal_Mlym-00000-of-000(…):   0%|          | 0.00/59.6M [00:00<?, ?B/s]

multihop_reasoning/mar_Deva-00000-of-000(…):   0%|          | 0.00/52.5M [00:00<?, ?B/s]

multihop_reasoning/npi_Deva-00000-of-000(…):   0%|          | 0.00/63.7M [00:00<?, ?B/s]

multihop_reasoning/ory_Orya-00000-of-000(…):   0%|          | 0.00/47.3M [00:00<?, ?B/s]

multihop_reasoning/pan_Guru-00000-of-000(…):   0%|          | 0.00/54.5M [00:00<?, ?B/s]

multihop_reasoning/tam_Taml-00000-of-000(…):   0%|          | 0.00/54.0M [00:00<?, ?B/s]

multihop_reasoning/tel_Telu-00000-of-000(…):   0%|          | 0.00/68.1M [00:00<?, ?B/s]

multihop_reasoning/urd_Arab-00000-of-000(…):   0%|          | 0.00/29.8M [00:00<?, ?B/s]

Generating asm_Beng split:   0%|          | 0/16145 [00:00<?, ? examples/s]

Generating ben_Beng split:   0%|          | 0/16384 [00:00<?, ? examples/s]

Generating eng_Latn split:   0%|          | 0/16384 [00:00<?, ? examples/s]

Generating guj_Gujr split:   0%|          | 0/16382 [00:00<?, ? examples/s]

Generating hin_Deva split:   0%|          | 0/16373 [00:00<?, ? examples/s]

Generating kan_Knda split:   0%|          | 0/16382 [00:00<?, ? examples/s]

Generating mal_Mlym split:   0%|          | 0/16382 [00:00<?, ? examples/s]

Generating mar_Deva split:   0%|          | 0/16384 [00:00<?, ? examples/s]

Generating npi_Deva split:   0%|          | 0/15676 [00:00<?, ? examples/s]

Generating ory_Orya split:   0%|          | 0/16379 [00:00<?, ? examples/s]

Generating pan_Guru split:   0%|          | 0/16381 [00:00<?, ? examples/s]

Generating tam_Taml split:   0%|          | 0/16383 [00:00<?, ? examples/s]

Generating tel_Telu split:   0%|          | 0/16383 [00:00<?, ? examples/s]

Generating urd_Arab split:   0%|          | 0/16382 [00:00<?, ? examples/s]

🔹 Loading subset: cultural_multihop_reasoning for Hindi...

cultural_multihop_reasoning/asm_Beng-000(…):   0%|          | 0.00/113M [00:00<?, ?B/s]

cultural_multihop_reasoning/ben_Beng-000(…):   0%|          | 0.00/113M [00:00<?, ?B/s]

cultural_multihop_reasoning/eng_Latn-000(…):   0%|          | 0.00/103M [00:00<?, ?B/s]

cultural_multihop_reasoning/guj_Gujr-000(…):   0%|          | 0.00/112M [00:00<?, ?B/s]

cultural_multihop_reasoning/hin_Deva-000(…):   0%|          | 0.00/113M [00:00<?, ?B/s]

cultural_multihop_reasoning/kan_Knda-000(…):   0%|          | 0.00/114M [00:00<?, ?B/s]

cultural_multihop_reasoning/mal_Mlym-000(…):   0%|          | 0.00/118M [00:00<?, ?B/s]

cultural_multihop_reasoning/mar_Deva-000(…):   0%|          | 0.00/114M [00:00<?, ?B/s]

cultural_multihop_reasoning/npi_Deva-000(…):   0%|          | 0.00/112M [00:00<?, ?B/s]

cultural_multihop_reasoning/ory_Orya-000(…):   0%|          | 0.00/114M [00:00<?, ?B/s]

cultural_multihop_reasoning/pan_Guru-000(…):   0%|          | 0.00/107M [00:00<?, ?B/s]

cultural_multihop_reasoning/tam_Taml-000(…):   0%|          | 0.00/116M [00:00<?, ?B/s]

cultural_multihop_reasoning/tel_Telu-000(…):   0%|          | 0.00/112M [00:00<?, ?B/s]

cultural_multihop_reasoning/urd_Arab-000(…):   0%|          | 0.00/107M [00:00<?, ?B/s]

Generating asm_Beng split:   0%|          | 0/26741 [00:00<?, ? examples/s]

Generating ben_Beng split:   0%|          | 0/26603 [00:00<?, ? examples/s]

Generating eng_Latn split:   0%|          | 0/26778 [00:00<?, ? examples/s]

Generating guj_Gujr split:   0%|          | 0/26768 [00:00<?, ? examples/s]

Generating hin_Deva split:   0%|          | 0/26731 [00:00<?, ? examples/s]

Generating kan_Knda split:   0%|          | 0/26709 [00:00<?, ? examples/s]

Generating mal_Mlym split:   0%|          | 0/26747 [00:00<?, ? examples/s]

Generating mar_Deva split:   0%|          | 0/26768 [00:00<?, ? examples/s]

Generating npi_Deva split:   0%|          | 0/26760 [00:00<?, ? examples/s]

Generating ory_Orya split:   0%|          | 0/26722 [00:00<?, ? examples/s]

Generating pan_Guru split:   0%|          | 0/26125 [00:00<?, ? examples/s]

Generating tam_Taml split:   0%|          | 0/26743 [00:00<?, ? examples/s]

Generating tel_Telu split:   0%|          | 0/26673 [00:00<?, ? examples/s]

Generating urd_Arab split:   0%|          | 0/26713 [00:00<?, ? examples/s]

🔹 Loading subset: dialog_gen for Hindi...

dialog_gen/asm_Beng-00000-of-00001.parqu(…):   0%|          | 0.00/99.3M [00:00<?, ?B/s]

dialog_gen/ben_Beng-00000-of-00001.parqu(…):   0%|          | 0.00/97.4M [00:00<?, ?B/s]

dialog_gen/eng_Latn-00000-of-00001.parqu(…):   0%|          | 0.00/101M [00:00<?, ?B/s]

dialog_gen/guj_Gujr-00000-of-00001.parqu(…):   0%|          | 0.00/87.8M [00:00<?, ?B/s]

dialog_gen/hin_Deva-00000-of-00001.parqu(…):   0%|          | 0.00/108M [00:00<?, ?B/s]

dialog_gen/kan_Knda-00000-of-00001.parqu(…):   0%|          | 0.00/104M [00:00<?, ?B/s]

dialog_gen/mal_Mlym-00000-of-00001.parqu(…):   0%|          | 0.00/109M [00:00<?, ?B/s]

dialog_gen/mar_Deva-00000-of-00001.parqu(…):   0%|          | 0.00/103M [00:00<?, ?B/s]

dialog_gen/npi_Deva-00000-of-00001.parqu(…):   0%|          | 0.00/96.0M [00:00<?, ?B/s]

dialog_gen/ory_Orya-00000-of-00001.parqu(…):   0%|          | 0.00/86.4M [00:00<?, ?B/s]

dialog_gen/pan_Guru-00000-of-00001.parqu(…):   0%|          | 0.00/87.4M [00:00<?, ?B/s]

dialog_gen/tam_Taml-00000-of-00001.parqu(…):   0%|          | 0.00/112M [00:00<?, ?B/s]

dialog_gen/tel_Telu-00000-of-00001.parqu(…):   0%|          | 0.00/103M [00:00<?, ?B/s]

dialog_gen/urd_Arab-00000-of-00001.parqu(…):   0%|          | 0.00/85.4M [00:00<?, ?B/s]

Generating asm_Beng split:   0%|          | 0/16120 [00:00<?, ? examples/s]

Generating ben_Beng split:   0%|          | 0/16372 [00:00<?, ? examples/s]

Generating eng_Latn split:   0%|          | 0/16384 [00:00<?, ? examples/s]

Generating guj_Gujr split:   0%|          | 0/16378 [00:00<?, ? examples/s]

Generating hin_Deva split:   0%|          | 0/16371 [00:00<?, ? examples/s]

Generating kan_Knda split:   0%|          | 0/16376 [00:00<?, ? examples/s]

Generating mal_Mlym split:   0%|          | 0/16374 [00:00<?, ? examples/s]

Generating mar_Deva split:   0%|          | 0/16383 [00:00<?, ? examples/s]

Generating npi_Deva split:   0%|          | 0/15663 [00:00<?, ? examples/s]

Generating ory_Orya split:   0%|          | 0/16367 [00:00<?, ? examples/s]

Generating pan_Guru split:   0%|          | 0/16376 [00:00<?, ? examples/s]

Generating tam_Taml split:   0%|          | 0/16379 [00:00<?, ? examples/s]

Generating tel_Telu split:   0%|          | 0/16380 [00:00<?, ? examples/s]

Generating urd_Arab split:   0%|          | 0/16365 [00:00<?, ? examples/s]

🔹 Loading subset: creative_writing for Hindi...

creative_writing/asm_Beng-00000-of-00001(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

creative_writing/ben_Beng-00000-of-00001(…):   0%|          | 0.00/44.9M [00:00<?, ?B/s]

creative_writing/eng_Latn-00000-of-00001(…):   0%|          | 0.00/58.5M [00:00<?, ?B/s]

creative_writing/guj_Gujr-00000-of-00001(…):   0%|          | 0.00/35.0M [00:00<?, ?B/s]

creative_writing/hin_Deva-00000-of-00001(…):   0%|          | 0.00/46.5M [00:00<?, ?B/s]

creative_writing/kan_Knda-00000-of-00001(…):   0%|          | 0.00/42.7M [00:00<?, ?B/s]

creative_writing/mal_Mlym-00000-of-00001(…):   0%|          | 0.00/45.0M [00:00<?, ?B/s]

creative_writing/mar_Deva-00000-of-00001(…):   0%|          | 0.00/45.1M [00:00<?, ?B/s]

creative_writing/npi_Deva-00000-of-00001(…):   0%|          | 0.00/35.9M [00:00<?, ?B/s]

creative_writing/ory_Orya-00000-of-00001(…):   0%|          | 0.00/37.2M [00:00<?, ?B/s]

creative_writing/pan_Guru-00000-of-00001(…):   0%|          | 0.00/41.3M [00:00<?, ?B/s]

creative_writing/tam_Taml-00000-of-00001(…):   0%|          | 0.00/46.8M [00:00<?, ?B/s]

creative_writing/tel_Telu-00000-of-00001(…):   0%|          | 0.00/45.6M [00:00<?, ?B/s]

creative_writing/urd_Arab-00000-of-00001(…):   0%|          | 0.00/29.4M [00:00<?, ?B/s]

Generating asm_Beng split:   0%|          | 0/16145 [00:00<?, ? examples/s]

Generating ben_Beng split:   0%|          | 0/16381 [00:00<?, ? examples/s]

Generating eng_Latn split:   0%|          | 0/16380 [00:00<?, ? examples/s]

Generating guj_Gujr split:   0%|          | 0/16381 [00:00<?, ? examples/s]

Generating hin_Deva split:   0%|          | 0/16374 [00:00<?, ? examples/s]

Generating kan_Knda split:   0%|          | 0/16383 [00:00<?, ? examples/s]

Generating mal_Mlym split:   0%|          | 0/16384 [00:00<?, ? examples/s]

Generating mar_Deva split:   0%|          | 0/16383 [00:00<?, ? examples/s]

Generating npi_Deva split:   0%|          | 0/15724 [00:00<?, ? examples/s]

Generating ory_Orya split:   0%|          | 0/16381 [00:00<?, ? examples/s]

Generating pan_Guru split:   0%|          | 0/16149 [00:00<?, ? examples/s]

Generating tam_Taml split:   0%|          | 0/16383 [00:00<?, ? examples/s]

Generating tel_Telu split:   0%|          | 0/16383 [00:00<?, ? examples/s]

Generating urd_Arab split:   0%|          | 0/16373 [00:00<?, ? examples/s]

✅ Combined Bengali Dataset Loaded: 140944 samples across all subsets.

In [11]:
import random
from datasets import Dataset

# 🔢 Desired sample size
TARGET_SIZE = 10_000
SEED = 42  # fixed seed for reproducibility

# 🧮 Current dataset size
total_size = len(train_dataset)
print(f"Total examples before sampling: {total_size}")

# ✅ Compute percentage retained
percentage = (TARGET_SIZE / total_size) * 100
print(f"Retaining {TARGET_SIZE} examples ({percentage:.2f}% of total)")

# 🎲 Randomly shuffle with fixed seed and select 10k examples
train_dataset = train_dataset.shuffle(seed=SEED).select(range(TARGET_SIZE))

# ✅ Check final size
print(f"Final dataset size: {len(train_dataset)}")

Total examples before sampling: 140944
Retaining 10000 examples (7.10% of total)
Final dataset size: 10000

In [12]:
def length_train(example):
    text = ""
    # The Updesh dataset stores messages as a list of {"role": ..., "content": ...}
    if "messages" in example and isinstance(example["messages"], list):
        text = " ".join([m["content"] for m in example["messages"] if "content" in m])
    return tokenizer(text, truncation=False, padding=False)

# 🔹 Tokenize a small sample to estimate lengths
tokenized_sample = train_dataset.select(range(2000)).map(length_train, batched=False)

# Compute lengths
lengths = tokenized_sample.map(lambda x: {"len": len(x["input_ids"])})
lengths_np = np.array(lengths["len"])

print("📏 Max length:", lengths_np.max())
print("📊 Mean length:", lengths_np.mean())
print("📈 99th percentile:", np.percentile(lengths_np, 99))

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

📏 Max length: 12288
📊 Mean length: 2643.887
📈 99th percentile: 7876.65

In [3]:
from transformers import PreTrainedTokenizerBase

MAX_SEQ_LENGTH = 1024

def tokenize_function(example, tokenizer: PreTrainedTokenizerBase):
    """
    Tokenizes a dataset example for causal LM fine-tuning (prompt + target),
    masking loss for prompt tokens only, ensuring the completion fits.
    """

    # Extract conversation parts
    prompt = ""
    completion = ""

    for msg in example["messages"]:
        if msg["role"] in ["system", "user"]:
            prompt += msg["content"] + " "
        elif msg["role"] == "assistant":
            completion = msg["content"].strip()
            break

    if not completion:
        return None  # skip examples without assistant response

    separator_token = tokenizer.eos_token or tokenizer.sep_token
    if separator_token is None:
        raise ValueError("Tokenizer must have an EOS or SEP token defined.")

    # Tokenize completion first (we must ensure it fits at the end)
    tokenized_completion = tokenizer(
        separator_token + " " + completion,
        add_special_tokens=False,
        truncation=True,
        max_length=MAX_SEQ_LENGTH // 2,  # rough upper bound for safety
        padding=False
    )

    # Then tokenize the prompt, but only up to the *remaining space*
    remaining_space = MAX_SEQ_LENGTH - len(tokenized_completion["input_ids"])
    tokenized_prompt = tokenizer(
        prompt.strip(),
        add_special_tokens=True,
        truncation=True,
        max_length=remaining_space,
        padding=False
    )

    # Combine
    full_input_ids = tokenized_prompt["input_ids"] + tokenized_completion["input_ids"]
    attention_mask = [1] * len(full_input_ids)

    # Pad final sequence
    padding_length = MAX_SEQ_LENGTH - len(full_input_ids)
    if padding_length > 0:
        full_input_ids += [tokenizer.pad_token_id] * padding_length
        attention_mask += [0] * padding_length

    # Mask out prompt tokens in labels
    labels = full_input_ids.copy()
    prompt_len = len(tokenized_prompt["input_ids"])
    for i in range(prompt_len):
        labels[i] = -100

    return {
        "input_ids": full_input_ids,
        "attention_mask": attention_mask,
        "labels": labels,
    }

In [14]:
# --- Assuming 'tokenizer' object has been loaded previously ---

# Apply the tokenization to the training dataset
train_dataset = train_dataset.map(
    tokenize_function,
    # Pass the 'tokenizer' as a keyword argument to tokenize_function
    fn_kwargs={"tokenizer": tokenizer},
    batched=False,
    remove_columns=train_dataset.column_names
)


print(f"Train Dataset (Tokenized): {train_dataset}")

Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

Train Dataset (Tokenized): Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 9996
})

In [15]:
from collections import Counter
print(Counter(train_dataset[0]["labels"]))

Counter({-100: 494, 240482: 66, 236168: 22, 1: 19, 236596: 16, 236180: 13, 28596: 11, 236272: 11, 236460: 11, 236389: 10, 183886: 9, 107520: 8, 236955: 8, 237265: 8, 244307: 8, 26706: 8, 240282: 7, 237547: 7, 241612: 7, 223359: 7, 235940: 7, 77014: 6, 237675: 6, 77577: 6, 38964: 6, 51715: 6, 24313: 6, 235269: 6, 211850: 6, 136882: 5, 39808: 5, 238980: 5, 64170: 5, 71913: 5, 238462: 5, 181774: 5, 240751: 5, 237273: 4, 97371: 4, 96437: 4, 66807: 4, 236821: 4, 58702: 4, 236843: 4, 226778: 4, 237767: 4, 106917: 4, 235976: 4, 237913: 3, 237890: 3, 125175: 3, 241756: 3, 187460: 3, 238565: 3, 238327: 3, 184814: 3, 213798: 3, 181194: 3, 115661: 3, 238105: 3, 238592: 3, 126105: 2, 78736: 2, 60648: 2, 239603: 2, 78149: 2, 106338: 2, 235290: 2, 159056: 2, 66205: 2, 59566: 2, 139957: 2, 192702: 2, 175384: 2, 35243: 2, 48818: 2, 79452: 2, 90106: 2, 64912: 2, 202381: 2, 238338: 2, 237642: 2, 44986: 2, 81542: 2, 236571: 2, 158494: 2, 53104: 2, 237462: 2, 98562: 1, 140115: 1, 160134: 1, 27577: 1, 228836: 1, 238370: 1, 238726: 1, 231874: 1, 239442: 1, 236677: 1, 205658: 1, 44666: 1, 161072: 1, 591: 1, 2018: 1, 97229: 1, 235275: 1, 229052: 1, 36674: 1, 165111: 1, 143213: 1, 240693: 1, 82893: 1, 146424: 1, 169584: 1, 235248: 1, 116501: 1, 188842: 1, 95230: 1, 186828: 1, 195385: 1, 131564: 1, 43982: 1, 27706: 1, 44663: 1, 79618: 1, 83364: 1, 28495: 1, 211326: 1, 220142: 1, 236739: 1, 81598: 1})

In [16]:
for i in range(3):
    #print(train_dataset[i]["input_ids"][275:300])
    print(train_dataset[i]["labels"][1000:1024])

[192702, 236739, 237265, 237767, 211850, 81598, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[24313, 240482, 236272, 43982, 236180, 238734, 240988, 236843, 237675, 236460, 240482, 77577, 51715, 100664, 235976, 82893, 66807, 237265, 235248, 240482, 235976, 238448, 236180, 235940]
[236389, 24313, 240482, 236272, 238565, 59566, 235940, 109, 238726, 236596, 237903, 236571, 235269, 187547, 161072, 236272, 237767, 236596, 44986, 241612, 236596, 51715, 90106, 236571]

In [17]:
# shape of the dataset
print("Shapes of the tokenized datasets:")
print(f"Training: {train_dataset.num_rows} rows, {len(train_dataset.column_names)} columns")



# View the dataset structure in detail
print(train_dataset)

Shapes of the tokenized datasets:
Training: 9996 rows, 3 columns
Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 9996
})

In [18]:
# For training dataset
input_lengths = [len(x["input_ids"]) for x in train_dataset]
label_lengths = [len(x["labels"]) for x in train_dataset]

print("Input lengths:", input_lengths[:20])   # first 20 examples
print("Label lengths:", label_lengths[:20])

print("Max input length:", max(input_lengths))
print("Max label length:", max(label_lengths))
print("Min input length:", min(input_lengths))
print("Min label length:", min(label_lengths))

Input lengths: [1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024]
Label lengths: [1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024]
Max input length: 1024
Max label length: 1024
Min input length: 1024
Min label length: 1024

# Training

In [19]:
import time
import torch
from transformers import Trainer, TrainingArguments, DataCollatorForLanguageModeling
from peft import LoraConfig, get_peft_model, TaskType, prepare_model_for_kbit_training

def train_model(model, tokenizer, train_dataset, use_lora=True):
    LANG_CODE = 'bn'
    """
    Train a causal LM model with optional LoRA, no evaluation.
    """
    # 🔧 Auto device
    if torch.cuda.is_available():
        device = torch.device("cuda")
    elif torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
    print(f"\n🖥️ Using device: {device}")

    torch.cuda.empty_cache()

    # Data collator for Causal LM
    data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

    # --- Optional LoRA ---
    if use_lora:
        print("🔹 LoRA enabled")
        lora_config = LoraConfig(
            r=8,
            lora_alpha=16,
            target_modules=["q_proj", "v_proj"],
            lora_dropout=0.05,
            bias="none",
            task_type=TaskType.CAUSAL_LM,
        )
        model = prepare_model_for_kbit_training(model)
        model = get_peft_model(model, lora_config)
        trainable, total = model.get_nb_trainable_parameters()
        print(f"Trainable: {trainable} | Total: {total} | "
              f"Percentage: {trainable / total * 100:.4f}%")
    else:
        print("⚙️ Full fine-tuning mode (LoRA disabled)")

    # Gradient checkpointing + no cache
    model.gradient_checkpointing_enable()
    if hasattr(model.config, "use_cache"):
        model.config.use_cache = False

    output_dir = f"./results-{int(time.time())}"

    training_args = TrainingArguments(
        output_dir=output_dir,
        seed = 42,
        per_device_train_batch_size=8,
        gradient_accumulation_steps=1,
        num_train_epochs=3,  # train exactly 3 epochs
        logging_steps=50,
        save_steps=200,
        save_total_limit=2,
        fp16=True,
        optim="paged_adamw_8bit",
        report_to="none",
    )

    # Trainer setup
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        tokenizer=tokenizer,
        data_collator=data_collator,
    )

    # ---- Train ----
    print("\n🚀 Starting Training...\n")
    trainer.train()

    # ---- Save final model ----
    final_model_path = f"./gemma_instruct_tune-{LANG_CODE}"
    model.save_pretrained(final_model_path, safe_serialization=True)
    tokenizer.save_pretrained(final_model_path)

    print(f"\n✅ Training complete! Model saved to: {final_model_path}")
    return trainer, model, final_model_path

In [ ]:
trainer, model, final_model_path = train_model(
    model,
    tokenizer,
    train_dataset,
    use_lora=True   # or False
)

🖥️ Using device: cuda
🔹 LoRA enabled
Trainable: 3211264 | Total: 8540892160 | Percentage: 0.0376%

/tmp/ipykernel_1612/3995345575.py:66: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 1}.

🚀 Starting Training...

# Saving

In [ ]:
# 1. Save the LoRA adapter weights (using the PeftModel object)
trainer.model.save_pretrained(final_model_path, safe_serialization=True)

# 2. Save the tokenizer (CRUCIAL for loading and generating text later)
# Assuming 'tokenizer' is the tokenizer object passed to the train_model function
tokenizer.save_pretrained(final_model_path)

# Fine tune on COSMMIC dataset

## load the dataset

In [2]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Path to the folder you saved earlier
final_model_path = './gemma_instruct_tune-bn'

# Load the model
model = AutoModelForCausalLM.from_pretrained(final_model_path, device_map="auto", torch_dtype=torch.float16)

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained(final_model_path)
tokenizer.pad_token = tokenizer.eos_token  # ensure padding works correctly

# Set device
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model.to(device)

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

GemmaForCausalLM(
  (model): GemmaModel(
    (embed_tokens): Embedding(256000, 3072, padding_idx=0)
    (layers): ModuleList(
      (0-27): 28 x GemmaDecoderLayer(
        (self_attn): GemmaAttention(
          (q_proj): lora.Linear(
            (base_layer): Linear(in_features=3072, out_features=4096, bias=False)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3072, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=4096, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (k_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (v_proj): lora.Linear(
            (base_layer): Linear(in_features=3072, out_features=4096, bias=False)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3072, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=4096, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (o_proj): Linear(in_features=4096, out_features=3072, bias=False)
        )
        (mlp): GemmaMLP(
          (gate_proj): Linear(in_features=3072, out_features=24576, bias=False)
          (up_proj): Linear(in_features=3072, out_features=24576, bias=False)
          (down_proj): Linear(in_features=24576, out_features=3072, bias=False)
          (act_fn): GELUActivation()
        )
        (input_layernorm): GemmaRMSNorm((3072,), eps=1e-06)
        (post_attention_layernorm): GemmaRMSNorm((3072,), eps=1e-06)
      )
    )
    (norm): GemmaRMSNorm((3072,), eps=1e-06)
    (rotary_emb): GemmaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=3072, out_features=256000, bias=False)
)

In [4]:
# load dataset
from datasets import load_dataset

dataset = load_dataset('json', data_files={
    'train': 'bangla_train.jsonl',
    'validation': 'bangla_valid.jsonl',
})

train_dataset = dataset['train']
val_dataset = dataset['validation']

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

In [ ]:
def length_train(example):
    text = ""
    # The Updesh dataset stores messages as a list of {"role": ..., "content": ...}
    if "messages" in example and isinstance(example["messages"], list):
        text = " ".join([m["content"] for m in example["messages"] if "content" in m])
    return tokenizer(text, truncation=False, padding=False)

# 🔹 Tokenize a small sample to estimate lengths
tokenized_sample = train_dataset.select(range(2000)).map(length_train, batched=False)

# Compute lengths
lengths = tokenized_sample.map(lambda x: {"len": len(x["input_ids"])})
lengths_np = np.array(lengths["len"])

print("📏 Max length:", lengths_np.max())
print("📊 Mean length:", lengths_np.mean())
print("📈 99th percentile:", np.percentile(lengths_np, 99))

In [ ]:
from transformers import PreTrainedTokenizerBase

MAX_SEQ_LENGTH = 1024

def tokenize_function(example, tokenizer: PreTrainedTokenizerBase):
    """
    Tokenizes a dataset example for causal LM fine-tuning (prompt + target),
    masking loss for prompt tokens only, ensuring the completion fits.
    """

    # Extract conversation parts
    prompt = ""
    completion = ""

    for msg in example["messages"]:
        if msg["role"] in ["system", "user"]:
            prompt += msg["content"] + " "
        elif msg["role"] == "assistant":
            completion = msg["content"].strip()
            break

    if not completion:
        return None  # skip examples without assistant response

    separator_token = tokenizer.eos_token or tokenizer.sep_token
    if separator_token is None:
        raise ValueError("Tokenizer must have an EOS or SEP token defined.")

    # Tokenize completion first (we must ensure it fits at the end)
    tokenized_completion = tokenizer(
        separator_token + " " + completion,
        add_special_tokens=False,
        truncation=True,
        max_length=MAX_SEQ_LENGTH // 2,  # rough upper bound for safety
        padding=False
    )

    # Then tokenize the prompt, but only up to the *remaining space*
    remaining_space = MAX_SEQ_LENGTH - len(tokenized_completion["input_ids"])
    tokenized_prompt = tokenizer(
        prompt.strip(),
        add_special_tokens=True,
        truncation=True,
        max_length=remaining_space,
        padding=False
    )

    # Combine
    full_input_ids = tokenized_prompt["input_ids"] + tokenized_completion["input_ids"]
    attention_mask = [1] * len(full_input_ids)

    # Pad final sequence
    padding_length = MAX_SEQ_LENGTH - len(full_input_ids)
    if padding_length > 0:
        full_input_ids += [tokenizer.pad_token_id] * padding_length
        attention_mask += [0] * padding_length

    # Mask out prompt tokens in labels
    labels = full_input_ids.copy()
    prompt_len = len(tokenized_prompt["input_ids"])
    for i in range(prompt_len):
        labels[i] = -100

    return {
        "input_ids": full_input_ids,
        "attention_mask": attention_mask,
        "labels": labels,
    }

In [7]:
# --- Assuming 'tokenizer' object has been loaded previously ---

# Apply the tokenization to the training dataset
train_dataset = train_dataset.map(
    tokenize_function,
    # Pass the 'tokenizer' as a keyword argument to tokenize_function
    fn_kwargs={"tokenizer": tokenizer},
    batched=False,
    remove_columns=train_dataset.column_names
)

# Apply the tokenization to the validation dataset
val_dataset = val_dataset.map(
    tokenize_function,
    # Pass the 'tokenizer' as a keyword argument to tokenize_function
    fn_kwargs={"tokenizer": tokenizer},
    batched=False,
    remove_columns=val_dataset.column_names
)

print(f"Train Dataset (Tokenized): {train_dataset}")
print(f"Validation Dataset (Tokenized): {val_dataset}")

Map:   0%|          | 0/501 [00:00<?, ? examples/s]

Map:   0%|          | 0/62 [00:00<?, ? examples/s]

Train Dataset (Tokenized): Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 501
})
Validation Dataset (Tokenized): Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 62
})

## training

In [8]:
import time
import torch
import numpy as np
from tqdm import tqdm
from transformers import (
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
)
from peft import (
    LoraConfig,
    get_peft_model,
    TaskType,
    prepare_model_for_kbit_training,
)
from polyglot.text import Text
import evaluate
import nltk

nltk.download("punkt")

# ------------------------------
# Language Code Variable
# ------------------------------
LANG_CODE = "bn"  # e.g., 'bn' for Bangla, 'mr' for Marathi

# ------------------------------
# Global Metric Setup
# ------------------------------
bertscore_model = "xlm-roberta-large"  # multilingual BERTScore model
rouge = evaluate.load("rouge")
bertscore = evaluate.load("bertscore")


# ------------------------------
# Polyglot Tokenization
# ------------------------------
def polyglot_tokenize(text):
    """Tokenize text using Polyglot based on the global LANG_CODE."""
    if not text:
        return ""
    return " ".join(Text(text, hint_language_code=LANG_CODE).words)


# ------------------------------
# Evaluation Function
# ------------------------------
def evaluate_model(model, tokenizer, dataset, device, max_target_length=200):
    """Evaluate the model on a validation/test dataset."""
    model.eval()
    predictions, references = [], []

    for batch in tqdm(dataset, desc="Evaluating"):
        input_ids = torch.tensor(batch["input_ids"]).unsqueeze(0).to(device)
        attention_mask = torch.tensor(batch["attention_mask"]).unsqueeze(0).to(device)
        labels = batch["labels"]

        input_length = (attention_mask[0] == 1).sum().item()

        with torch.no_grad():
            output_ids = model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                max_new_tokens=max_target_length,
                num_beams=5,
                early_stopping=True,
                pad_token_id=tokenizer.pad_token_id,
            )

        # Strip prompt portion
        generated_tokens = output_ids[0][input_length:]
        pred = tokenizer.decode(generated_tokens, skip_special_tokens=True)

        # Decode reference
        label_ids = [t for t in labels if t != -100]
        ref = tokenizer.decode(label_ids, skip_special_tokens=True)

        pred = polyglot_tokenize(pred).strip()
        ref = polyglot_tokenize(ref).strip()

        if ref:
            predictions.append(pred)
            references.append(ref)

    # ---- Compute metrics ----
    rouge_score = rouge.compute(predictions=predictions, references=references, use_stemmer=False)
    bertscore_results = bertscore.compute(
        predictions=predictions,
        references=references,
        lang=LANG_CODE,  # use global LANG_CODE here
        model_type=bertscore_model,
    )

    print("\n📊 Validation Metrics:")
    for key in ["rouge1", "rouge2", "rougeL"]:
        print(f"  {key}: {rouge_score[key]:.4f}")
    print(f"  BERTScore (F1): {np.mean(bertscore_results['f1']):.4f}")

    return rouge_score, bertscore_results


# ------------------------------
# Training Function
# ------------------------------
def train_model(model, tokenizer, train_dataset, val_dataset, use_lora=True):
    """
    Train a summarization model with optional LoRA
    and evaluate ROUGE + BERTScore once after all epochs.
    """
    # 🔧 Auto device
    if torch.cuda.is_available():
        device = torch.device("cuda")
    elif torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
    print(f"\n🖥️ Using device: {device}")

    torch.cuda.empty_cache()

    # Data collator for Causal LM
    data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

    # --- Optional LoRA ---
    if use_lora:
        print("🔹 LoRA enabled")
        lora_config = LoraConfig(
            r=8,
            lora_alpha=16,
            target_modules=["q_proj", "v_proj"],
            lora_dropout=0.05,
            bias="none",
            task_type=TaskType.CAUSAL_LM,
        )
        model = prepare_model_for_kbit_training(model)
        model = get_peft_model(model, lora_config)
        trainable, total = model.get_nb_trainable_parameters()
        print(f"Trainable: {trainable} | Total: {total} | "
              f"Percentage: {trainable / total * 100:.4f}%")
    else:
        print("⚙️ Full fine-tuning mode (LoRA disabled)")

    # Gradient checkpointing + no cache
    model.gradient_checkpointing_enable()
    if hasattr(model.config, "use_cache"):
        model.config.use_cache = False

    output_dir = f"./results-{int(time.time())}"

    training_args = TrainingArguments(
        output_dir=output_dir,
        per_device_train_batch_size=2,
        per_device_eval_batch_size=2,
        gradient_accumulation_steps=4,
        num_train_epochs=3,  # will train exactly 3 epochs
        logging_steps=50,
        save_steps=200,
        save_total_limit=2,
        fp16=True,
        optim="paged_adamw_8bit",
        report_to="none",
    )

    # Trainer setup
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        tokenizer=tokenizer,
        data_collator=data_collator,
    )

    # ---- Train ----
    print("\n🚀 Starting Training...\n")
    trainer.train()  # runs for num_train_epochs automatically

    # ---- Final Evaluation ----
    print("\n🧾 Final Evaluation on Validation Dataset...")
    rouge_score, bertscore_results = evaluate_model(model, tokenizer, val_dataset, device)

    # ---- Save ----
    final_model_path = f"./gemma-Code-Finetune-{LANG_CODE}"
    model.save_pretrained(final_model_path, safe_serialization=True)
    tokenizer.save_pretrained(final_model_path)

    print(f"\n✅ Training complete! Model saved to: {final_model_path}")
    return trainer, model, final_model_path

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

In [9]:
trainer, model, final_model_path = train_model(
    model,
    tokenizer,
    train_dataset,
    val_dataset,
    use_lora=True   # or False
)

🖥️ Using device: cuda
🔹 LoRA enabled
Trainable: 3211264 | Total: 8540892160 | Percentage: 0.0376%

/venv/main/lib/python3.10/site-packages/peft/mapping_func.py:73: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/venv/main/lib/python3.10/site-packages/peft/tuners/tuners_utils.py:196: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
/tmp/ipykernel_5152/4152775977.py:165: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
The model is already on multiple devices. Skipping the move to device specified in `args`.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 1}.

🚀 Starting Training...

🧾 Final Evaluation on Validation Dataset...

Evaluating: 100%|██████████| 62/62 [29:42<00:00, 28.76s/it]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/616 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

📊 Validation Metrics:
  rouge1: 0.0883
  rouge2: 0.0484
  rougeL: 0.0887
  BERTScore (F1): 0.9146

✅ Training complete! Model saved to: ./gemma-Code-Finetune-bn

In [10]:
# 1. Save the LoRA adapter weights (using the PeftModel object)
trainer.model.save_pretrained(final_model_path, safe_serialization=True)

# 2. Save the tokenizer (CRUCIAL for loading and generating text later)
# Assuming 'tokenizer' is the tokenizer object passed to the train_model function
tokenizer.save_pretrained(final_model_path)

('./gemma-Code-Finetune-bn/tokenizer_config.json',
 './gemma-Code-Finetune-bn/special_tokens_map.json',
 './gemma-Code-Finetune-bn/tokenizer.json')

# Inference on test dataset

In [4]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Path to the folder you saved earlier
final_model_path = './gemma-Code-Finetune-bn'

# Load the model
model = AutoModelForCausalLM.from_pretrained(final_model_path, device_map="auto", torch_dtype=torch.float16)

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained(final_model_path)
tokenizer.pad_token = tokenizer.eos_token  # ensure padding works correctly

# Set device
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
#model.to(device)

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

## load the dataset

In [5]:
from datasets import load_dataset

# Load test dataset
test_file = "bangla_test.jsonl"
dataset = load_dataset("json", data_files={"test": test_file})
test_dataset = dataset["test"]

from transformers import PreTrainedTokenizerBase

MAX_SEQ_LENGTH = 1024

def tokenize_function(example, tokenizer: PreTrainedTokenizerBase):
    """
    Tokenizes a dataset example for causal LM fine-tuning (prompt + target),
    masking loss for prompt tokens only, ensuring the completion fits.
    """

    # Extract conversation parts
    prompt = ""
    completion = ""

    for msg in example["messages"]:
        if msg["role"] in ["system", "user"]:
            prompt += msg["content"] + " "
        elif msg["role"] == "assistant":
            completion = msg["content"].strip()
            break

    if not completion:
        return None  # skip examples without assistant response

    separator_token = tokenizer.eos_token or tokenizer.sep_token
    if separator_token is None:
        raise ValueError("Tokenizer must have an EOS or SEP token defined.")

    # Tokenize completion first (we must ensure it fits at the end)
    tokenized_completion = tokenizer(
        separator_token + " " + completion,
        add_special_tokens=False,
        truncation=True,
        max_length=MAX_SEQ_LENGTH // 2,  # rough upper bound for safety
        padding=False
    )

    # Then tokenize the prompt, but only up to the *remaining space*
    remaining_space = MAX_SEQ_LENGTH - len(tokenized_completion["input_ids"])
    tokenized_prompt = tokenizer(
        prompt.strip(),
        add_special_tokens=True,
        truncation=True,
        max_length=remaining_space,
        padding=False
    )

    # Combine
    full_input_ids = tokenized_prompt["input_ids"] + tokenized_completion["input_ids"]
    attention_mask = [1] * len(full_input_ids)

    # Pad final sequence
    padding_length = MAX_SEQ_LENGTH - len(full_input_ids)
    if padding_length > 0:
        full_input_ids += [tokenizer.pad_token_id] * padding_length
        attention_mask += [0] * padding_length

    # Mask out prompt tokens in labels
    labels = full_input_ids.copy()
    prompt_len = len(tokenized_prompt["input_ids"])
    for i in range(prompt_len):
        labels[i] = -100

    return {
        "input_ids": full_input_ids,
        "attention_mask": attention_mask,
        "labels": labels,
    }


# Apply tokenization
test_dataset = test_dataset.map(
    tokenize_function,
    fn_kwargs={"tokenizer": tokenizer},
    batched=False,
    # REMOVE only the original columns (before tokenization)
    remove_columns=["messages"]
)

print(test_dataset)

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 64
})

In [6]:
from collections import Counter
print(Counter(test_dataset[0]["labels"]))

Counter({-100: 737, 35243: 12, 236085: 12, 236460: 9, 237675: 9, 48818: 8, 235976: 8, 21716: 6, 237265: 6, 236180: 6, 235940: 6, 236821: 6, 236389: 5, 237767: 5, 98562: 5, 27706: 5, 236843: 4, 238782: 4, 236955: 4, 238448: 4, 238105: 4, 26706: 4, 103292: 4, 89254: 4, 28596: 4, 24313: 3, 90106: 3, 162881: 3, 228994: 3, 106338: 3, 130290: 3, 39808: 3, 32000: 3, 237890: 3, 43982: 3, 236272: 3, 51263: 3, 242464: 3, 44986: 3, 91570: 3, 81542: 2, 115964: 2, 77577: 2, 44663: 2, 58702: 2, 28495: 2, 192702: 2, 121114: 2, 116501: 2, 238592: 2, 238980: 2, 59566: 2, 237913: 2, 71913: 2, 36674: 2, 238565: 2, 128787: 2, 238531: 2, 57282: 2, 236677: 2, 164497: 2, 1: 1, 142389: 1, 237462: 1, 76997: 1, 77014: 1, 186828: 1, 183644: 1, 26599: 1, 181194: 1, 213798: 1, 97371: 1, 68932: 1, 79452: 1, 51715: 1, 241612: 1, 240751: 1, 116041: 1, 173135: 1, 160134: 1, 232058: 1, 218213: 1, 178845: 1, 236168: 1, 241605: 1, 205658: 1, 146424: 1, 113470: 1, 38964: 1, 237642: 1, 236596: 1, 238058: 1, 159056: 1, 183886: 1, 195866: 1, 78149: 1, 114398: 1, 119877: 1, 221997: 1, 242264: 1, 235269: 1, 239001: 1, 53104: 1, 198301: 1, 235248: 1, 240638: 1, 241140: 1, 27577: 1, 89513: 1, 215352: 1, 181774: 1, 95230: 1, 238327: 1, 223359: 1, 238734: 1, 215306: 1, 44666: 1})

In [7]:
from statistics import mean

# Ensure test_dataset is already tokenized
target_lengths = []

for example in test_dataset:
    labels = example["labels"]
    # Count non-masked tokens (-100 are masked)
    target_len = sum(1 for t in labels if t != -100)
    target_lengths.append(target_len)

avg_target_length = mean(target_lengths)
min_target_length = min(target_lengths)
max_target_length = max(target_lengths)

print(f"Target sequence lengths in test dataset:")
print(f"  Minimum: {min_target_length} tokens")
print(f"  Maximum: {max_target_length} tokens")
print(f"  Average: {avg_target_length:.2f} tokens")

Target sequence lengths in test dataset:
  Minimum: 154 tokens
  Maximum: 512 tokens
  Average: 320.95 tokens

In [8]:
import torch
import numpy as np
from tqdm import tqdm
from polyglot.text import Text
from transformers import PreTrainedTokenizer
import evaluate
import nltk
nltk.download('punkt')

# --- CONFIGURABLE LANGUAGE CODE ---
LANG_CODE = "bn"  # Change this to "mr", "hi", etc. as needed

# --- BERTScore model type ---
bertscore_model = "xlm-roberta-large"  # Multilingual checkpoint

# Initialize metrics
rouge = evaluate.load("rouge")
bertscore = evaluate.load("bertscore")

def polyglot_tokenize(text):
    """Tokenize using Polyglot for Indic scripts."""
    if not text:
        return ""
    return " ".join(Text(text, hint_language_code=LANG_CODE).words)

def evaluate_model(model, tokenizer: PreTrainedTokenizer, test_dataset, device, max_target_length=200):
    model.eval()
    predictions = []
    references = []

    for idx, batch in enumerate(tqdm(test_dataset, desc="Evaluating")):
        input_ids_list = batch["input_ids"]
        attention_mask_list = batch["attention_mask"]

        input_ids = torch.tensor(input_ids_list).unsqueeze(0).to(device)
        attention_mask = torch.tensor(attention_mask_list).unsqueeze(0).to(device)

        input_length = len(input_ids_list)

        with torch.no_grad():
            output_ids = model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                max_new_tokens=max_target_length,
                num_beams=5,
                early_stopping=True,
                pad_token_id=tokenizer.pad_token_id,
            )

        # Strip prompt from generated output
        generated_tokens = output_ids[0][input_length:]
        pred = tokenizer.decode(generated_tokens, skip_special_tokens=True)

        # Handle masked labels (-100)
        label_ids = [token_id for token_id in batch["labels"] if token_id != -100]
        ref = tokenizer.decode(label_ids, skip_special_tokens=True)

        # Tokenize using Polyglot
        pred = polyglot_tokenize(pred).strip()
        ref = polyglot_tokenize(ref).strip()

        predictions.append(pred)
        references.append(ref)

        # Print lengths per sample
        predicted_seq_len = len(generated_tokens)
        target_seq_len = len(label_ids)
        print(f"\nSample {idx+1}:")
        print(f"  Input sequence length:    {input_length}")
        print(f"  Predicted sequence length:{predicted_seq_len}")
        print(f"  Target sequence length:   {target_seq_len}")

    # Filter out empty references
    valid_predictions = []
    valid_references = []
    for p, r in zip(predictions, references):
        if r.strip():
            valid_predictions.append(p)
            valid_references.append(r)
        else:
            tqdm.write("Warning: Skipping an example due to empty reference.")

    # Compute ROUGE
    rouge_score = rouge.compute(
        predictions=valid_predictions,
        references=valid_references,
        use_stemmer=False
    )

    # Compute BERTScore
    bertscore_results = bertscore.compute(
        predictions=valid_predictions,
        references=valid_references,
        lang=LANG_CODE,
        model_type=bertscore_model
    )

    # Print results
    print("\n===== FINAL EVALUATION METRICS =====")
    print("ROUGE scores:")
    for key in ["rouge1", "rouge2", "rougeL"]:
        score = rouge_score[key]
        print(f"{key}: {score:.4f}")

    print("\nBERTScore:")
    print(f"Precision: {np.mean(bertscore_results['precision']):.4f}")
    print(f"Recall:    {np.mean(bertscore_results['recall']):.4f}")
    print(f"F1:        {np.mean(bertscore_results['f1']):.4f}")

    return rouge_score, bertscore_results

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
rouge_score, bertscore_results = evaluate_model(
    model,
    tokenizer,
    test_dataset,
    device,
    max_target_length=300
)

Evaluating:   2%|▏         | 1/64 [00:20<21:59, 20.95s/it]

Sample 1:
  Input sequence length:    1024
  Predicted sequence length:300
  Target sequence length:   287

Evaluating:   3%|▎         | 2/64 [00:39<20:03, 19.41s/it]

Sample 2:
  Input sequence length:    1024
  Predicted sequence length:264
  Target sequence length:   273

Evaluating:   5%|▍         | 3/64 [00:59<20:09, 19.82s/it]

Sample 3:
  Input sequence length:    1024
  Predicted sequence length:300
  Target sequence length:   252

Evaluating:   6%|▋         | 4/64 [01:19<20:02, 20.03s/it]

Sample 4:
  Input sequence length:    1024
  Predicted sequence length:300
  Target sequence length:   278

Evaluating:   8%|▊         | 5/64 [01:24<14:08, 14.38s/it]

Sample 5:
  Input sequence length:    1024
  Predicted sequence length:47
  Target sequence length:   229

Evaluating:   9%|▉         | 6/64 [01:44<15:54, 16.45s/it]

Sample 6:
  Input sequence length:    1024
  Predicted sequence length:300
  Target sequence length:   263

Evaluating:  11%|█         | 7/64 [02:05<16:53, 17.77s/it]

Sample 7:
  Input sequence length:    1024
  Predicted sequence length:300
  Target sequence length:   417

Evaluating:  12%|█▎        | 8/64 [02:25<17:24, 18.64s/it]

Sample 8:
  Input sequence length:    1024
  Predicted sequence length:300
  Target sequence length:   256

Evaluating:  14%|█▍        | 9/64 [02:46<17:37, 19.23s/it]

Sample 9:
  Input sequence length:    1024
  Predicted sequence length:300
  Target sequence length:   336

Evaluating:  16%|█▌        | 10/64 [03:02<16:29, 18.32s/it]

Sample 10:
  Input sequence length:    1024
  Predicted sequence length:238
  Target sequence length:   324

Evaluating:  17%|█▋        | 11/64 [03:19<15:48, 17.89s/it]

Sample 11:
  Input sequence length:    1024
  Predicted sequence length:247
  Target sequence length:   247

Evaluating:  19%|█▉        | 12/64 [03:39<16:03, 18.52s/it]

Sample 12:
  Input sequence length:    1024
  Predicted sequence length:217
  Target sequence length:   499

Evaluating:  20%|██        | 13/64 [03:57<15:42, 18.48s/it]

Sample 13:
  Input sequence length:    1024
  Predicted sequence length:269
  Target sequence length:   363

Evaluating:  22%|██▏       | 14/64 [04:18<15:54, 19.09s/it]

Sample 14:
  Input sequence length:    1024
  Predicted sequence length:300
  Target sequence length:   345

Evaluating:  23%|██▎       | 15/64 [04:22<11:58, 14.66s/it]

Sample 15:
  Input sequence length:    1024
  Predicted sequence length:55
  Target sequence length:   320

Evaluating:  25%|██▌       | 16/64 [04:43<13:08, 16.42s/it]

Sample 16:
  Input sequence length:    1024
  Predicted sequence length:300
  Target sequence length:   418

In [ ]:
from huggingface_hub import login

login()   # You'll be asked for your Hugging Face token

from huggingface_hub import create_repo, upload_folder

# 🔹 Change these values before running:
MODEL_DIR = "./gemma-Code-Finetune-te"   # Folder you saved after training

REPO_NAME = "gemma-Code-Finetune-te"     # You can rename if needed

repo_id = f"{REPO_NAME}"

# ✅ 1. Create repo if not exists
create_repo(repo_id, exist_ok=True)

# ✅ 2. Upload model + tokenizer folder
upload_folder(
    folder_path=MODEL_DIR,
    repo_id=repo_id,
    commit_message="Upload LoRA fine-tuned Gemma model"
)

print(f"✅ Model pushed successfully to https://huggingface.co/{repo_id}")